### ISSUE TITLE
Getting P_LCDM(k) from CAMB

### ISSUE THREAD

**Issue by Alkistis** [LSSTDESC/mgemu#1]
Hi @nesar and @gvalogia I've been looking at your wonderful emulator and I have a small question. I get PMG(k)/PLCDM(k) from the emulator, and if I want to use CAMB to get PLCDM(k) -and then multiply to get PMG(k)- am I right that this should be CAMB with HALOFIT (Takahashi et al. 2012)?

**Comment by gvalogia** [comment]
Thanks a lot for your interest in our emulator @Alkistis ! Yes, indeed, the output ratio would need to be multiplied by a nonlinear prediction (eg halofit from CAMB as you said) so that you get the nonlinear MG P(k)

**Comment by Alkistis** [comment]
thanks @gvalogia for the quick reply! I also wanted to clarify the `h` caution issue. For example if one wants to run an MCMC, is the suggestion that `h` should not be varied so that the variation in `Omh2` practically comes from changing `Om`? Or have I misunderstood? thanks in advance :-)

**Comment by nesar** [comment]
@Alkistis that is correct. The experimental design of this emulator has a varying `Omh2` but `h` is kept constant across the COLA simulations. Hence if you want to run MCMC, it's recommended not to vary `h`. Or to keep the range of variation extremely narrow. Some discussion on how the mismatch in `h` effects the power spectra boost is given in Section IV B of the accompanying [paper](https://arxiv.org/abs/2010.00596)

**Comment by nesar** [comment]
@Alkistis Also, this [branch](https://github.com/LSSTDESC/mgemu/tree/Speedup) is much better optimized in terms of memory, if you want to run MCMC.

**Comment by Alkistis** [comment]
@nesar thank you so much for these replies and for recommending the fast branch, much appreciated!
