### ISSUE TITLE
installation issue (and solution): 'Dataset' has no attribute 'value'

### ISSUE THREAD

**Issue by Alkistis** [LSSTDESC/mgemu#2]
Hi @nesar and @gvalogia just wanted to mention this issue I encountered while installing `mgemu` in a clean environment on a new MacBook Pro. I attach a screenshot below (with errors when running the test suite) which was solved by downgrading h5py with `pip3 install h5py=='2.9.0'`. I imagine this is not the optimal solution but I thought to report it here.

<img width="665" alt="Docs httpsdocs pytest orgenstablewarnings html" src="https://user-images.githubusercontent.com/10515921/141065453-bde4c405-dc22-4560-8150-0b2a717d6177.png">

**Comment by nesar** [comment]
@Alkistis we noticed this change in the new h5py version. Thanks for pointing out. We will update the README file for now. Next versions of the emulator should be compatible with the latext h5py.

**Comment by Alkistis** [comment]
thank you @nesar!
